cloud:
  aws:
    credentials:
      accessKey: AKIAVK5CHHBEHXGPS67H     # AWS IAM AccessKey 적기
      secretKey: jLpv3jjVQIXNMgZoV5Q/gSPVrP4p+Gxu3r9KV7ng   # AWS IAM SecretKey 적기
    s3:
      bucket: reborn-bucket    # ex) marryting-gyunny
      dir: S3 디렉토리 이름 # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false